# Generated by Django 4.2.1 on 2023-05-26 05:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurants",
            fields=[
                (
                    "id",
                    models.TextField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(4),
                        ]
                    ),
                ),
                ("name", models.TextField(blank=True)),
                ("site", models.TextField(blank=True)),
                ("email", models.TextField(blank=True)),
                ("phone", models.TextField(blank=True)),
                ("street", models.TextField(blank=True)),
                ("city", models.TextField(blank=True)),
                ("state", models.TextField(blank=True)),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
