# Generated by Django 4.2.1 on 2023-05-30 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud_api", "0003_file_rename_restaurants_restaurant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="city",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="email",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="phone",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="site",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="state",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="street",
            field=models.TextField(),
        ),
    ]
